# Generated by Django 5.2.1 on 2025-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scannedurl_urlscan_is_dangerous_alter_urlscan_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='MAC address in the format XX:XX:XX:XX:XX:XX', max_length=17, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Optional human-friendly name for this device', max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
