# Generated by Django 5.2.1 on 2025-06-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_intrusionalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLScan',
        ),
    ]
