# Generated by Django 5.2.1 on 2025-06-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_urlscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('result', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_dangerous', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='scannedurl',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
