# Generated by Django 5.2.1 on 2025-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_urlscan_scannedurl_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_phishing', models.BooleanField()),
                ('suspicious_keywords', models.JSONField()),
                ('links', models.JSONField()),
                ('sender_reputation', models.CharField(max_length=50)),
                ('analysis_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
