# Generated by Django 5.2.1 on 2025-06-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailanalysis',
            name='html_elements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='phishing_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='suspicious_domains',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='suspicious_keywords',
            field=models.JSONField(default=list),
        ),
    ]
