// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqb-7YH-Gw7BCjmspmdZ02ITed9ELvqw',
    appId: '1:407833646649:web:56a894ed805f7ba6ab5fe8',
    messagingSenderId: '407833646649',
    projectId: 'cybershield-d2749',
    authDomain: 'cybershield-d2749.firebaseapp.com',
    storageBucket: 'cybershield-d2749.firebasestorage.app',
    measurementId: 'G-H97MW5PVK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkEIIPvjrq7O0MxEp_HTAoEhM21_JSA_Y',
    appId: '1:407833646649:android:74ef668797f8e638ab5fe8',
    messagingSenderId: '407833646649',
    projectId: 'cybershield-d2749',
    storageBucket: 'cybershield-d2749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXq4STYXA169fWAKeSLawnzN7H_gqc4OU',
    appId: '1:407833646649:ios:05d2a159b4769470ab5fe8',
    messagingSenderId: '407833646649',
    projectId: 'cybershield-d2749',
    storageBucket: 'cybershield-d2749.firebasestorage.app',
    iosBundleId: 'com.example.cybershield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXq4STYXA169fWAKeSLawnzN7H_gqc4OU',
    appId: '1:407833646649:ios:05d2a159b4769470ab5fe8',
    messagingSenderId: '407833646649',
    projectId: 'cybershield-d2749',
    storageBucket: 'cybershield-d2749.firebasestorage.app',
    iosBundleId: 'com.example.cybershield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPqb-7YH-Gw7BCjmspmdZ02ITed9ELvqw',
    appId: '1:407833646649:web:cccfff40aa9ebf93ab5fe8',
    messagingSenderId: '407833646649',
    projectId: 'cybershield-d2749',
    authDomain: 'cybershield-d2749.firebaseapp.com',
    storageBucket: 'cybershield-d2749.firebasestorage.app',
    measurementId: 'G-45Z0FRJGN9',
  );
}
